name: ci-build
on:
  push:

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true
      
      - run: go install github.com/sanbornm/go-selfupdate/cmd/go-selfupdate
      - run: go get ./cmd/bedrocktool

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: build
        run: make -j dists updates

      - name: Deploy with rsync
        run: rsync -avz ./public/ olebeck@${{ secrets.SSH_HOST }}:/var/www/updates/bedrocktool-mass-skin/

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.get-latest-tag.outputs.tag }}
          files: dist/*
          prerelease: false
